import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os

st.set_page_config(page_title="Interactive What-If Simulation", layout="wide")

st.title("Scenario-based Digital Twin Simulation")
st.markdown("""
Explore how specific theoretical operational interventions affect warehouse fulfillment KPIs. 
**Note:** These are pre-computed, deterministic what-if simulation results generated by the synthetic digital twin, NOT live operational predictions or real historical data.
""")

@st.cache_data
def load_simulation_data():
    try:
        if not os.path.exists("data/dashboard/dashboard_scenario_comparison.csv") or \
           not os.path.exists("data/dashboard/dashboard_kpis.csv") or \
           not os.path.exists("data/dashboard/dashboard_stage_metrics.csv"):
            return None, None, None
            
        comp_df = pd.read_csv("data/dashboard/dashboard_scenario_comparison.csv")
        kpi_df = pd.read_csv("data/dashboard/dashboard_kpis.csv")
        stage_df = pd.read_csv("data/dashboard/dashboard_stage_metrics.csv")
        
        return comp_df, kpi_df, stage_df
    except Exception as e:
        st.error(f"Error loading dashboard data: {e}")
        return None, None, None

comp_df, kpi_df, stage_df = load_simulation_data()

if comp_df is None or kpi_df is None:
    st.warning("Dashboard data is unavailable. Please ensure all required CSV files are present in data/dashboard/.")
else:
    baseline_kpis = kpi_df[kpi_df["scenario"] == "baseline"].iloc[0]
    baseline_stage = stage_df[stage_df["scenario"] == "baseline"]
    
    st.sidebar.header("What-If Controls")
    
    # Get available scenarios from comparison df
    available_scenarios = comp_df["scenario_label"].tolist()
    
    # Let user select one scenario to compare against baseline
    selected_label = st.sidebar.selectbox("Select Scenario to Simulate:", available_scenarios, index=0)
    
    selected_row = comp_df[comp_df["scenario_label"] == selected_label].iloc[0]
    scenario_id = selected_row["scenario"]
    
    st.header(f"Simulating: {selected_label}")
    
    # Dynamic Explanation
    st.markdown("### Scenario Hypothesis & Effect")
    if scenario_id == "dispatch_plus_1":
        explanation = "**Dispatch +1 Worker:** Adds localized capacity to the primary active bottleneck. This reduces downstream congestion and successfully improves overall system flow time."
    elif scenario_id == "picking_plus_5":
        explanation = "**Picking +5 Workers:** Massively improves Picking capacity locally, but produces negligible system-level flow-time improvement because the downstream Dispatch bottleneck remains constrained."
    elif scenario_id == "packing_plus_2":
        explanation = "**Packing +2 Workers:** Adds capacity to an already unconstrained stage. As expected, this has a negligible system-level impact because Packing was never a bottleneck."
    elif scenario_id == "productivity_plus_10":
        explanation = "**Productivity +10%:** Models a theoretical global 10% efficiency gain across all workers, directly reducing processing times and subsequently lowering waiting queues."
    elif scenario_id == "extended_shift":
        explanation = "**Extended Shift (10h to 12h):** Expands the daily operating window boundary. This significantly reduces overnight shift-boundary waiting and yields the largest overall flow time improvement."
    else:
        explanation = f"**{selected_label}:** {selected_row.get('description', 'Simulated operational intervention.')}"
        
    st.info(explanation)
    
    st.divider()
    
    # KPI Comparisons
    st.header("Key Performance Indicators (vs Baseline)")
    
    # Columns for metrics
    c1, c2, c3, c4 = st.columns(4)
    
    def format_time(seconds):
        return f"{seconds / 3600:.2f}h"
        
    def render_metric(col, title, base_val, new_val, change_pct, invert_color=False):
        delta_color = "normal"
        if invert_color:
            delta_color = "inverse"
            
        # We want negative flow/wait times to be green (inverse)
        # We want positive SLA to be green (normal)
        
        col.metric(
            label=title,
            value=format_time(new_val) if "SLA" not in title else f"{new_val:.1f}%",
            delta=f"{change_pct:.2f}%",
            delta_color=delta_color
        )
    
    # Flow Time
    render_metric(
        c1, "Mean Flow Time", 
        baseline_kpis["mean_flow_time_seconds"], 
        selected_row["mean_flow_time_seconds"], 
        selected_row["mean_flow_time_change_percent"], 
        invert_color=True
    )
    
    # P95 Flow Time
    render_metric(
        c2, "P95 Flow Time", 
        baseline_kpis["p95_flow_time_seconds"], 
        selected_row["p95_flow_time_seconds"], 
        selected_row["p95_flow_time_change_percent"], 
        invert_color=True
    )
    
    # Wait Time
    render_metric(
        c3, "Mean Waiting Time", 
        baseline_kpis["mean_waiting_time_seconds"], 
        selected_row["mean_waiting_time_seconds"], 
        selected_row["mean_waiting_time_change_percent"], 
        invert_color=True
    )
    
    # Processing Time (if available directly or derive from stage df)
    # Using the raw overall KPI if we loaded it, but comparison_df might not have mean processing time change
    # Let's derive it from kpi_df
    scen_kpi = kpi_df[kpi_df["scenario"] == scenario_id].iloc[0]
    base_proc = baseline_kpis["mean_processing_time_seconds"]
    new_proc = scen_kpi["mean_processing_time_seconds"]
    proc_change_pct = ((new_proc - base_proc) / base_proc * 100) if base_proc > 0 else 0
    
    render_metric(
        c4, "Mean Processing Time", 
        base_proc, 
        new_proc, 
        proc_change_pct, 
        invert_color=True
    )
    
    st.divider()
    
    # Visual Comparison
    st.header("Visual Comparison")
    
    colA, colB = st.columns(2)
    
    # Prepare comparison dataframe for charts
    chart_df = pd.DataFrame({
        "Scenario": ["Baseline", selected_label],
        "Mean Flow Time (s)": [baseline_kpis["mean_flow_time_seconds"], selected_row["mean_flow_time_seconds"]],
        "Mean Waiting Time (s)": [baseline_kpis["mean_waiting_time_seconds"], selected_row["mean_waiting_time_seconds"]]
    })
    
    with colA:
        fig1 = px.bar(
            chart_df,
            x="Scenario",
            y="Mean Flow Time (s)",
            title="Mean Flow Time Comparison",
            color="Scenario",
            color_discrete_sequence=["#7F7F7F", "#1F77B4"],
            text_auto='.2s'
        )
        st.plotly_chart(fig1, use_container_width=True)
        
    with colB:
        fig2 = px.bar(
            chart_df,
            x="Scenario",
            y="Mean Waiting Time (s)",
            title="Mean Waiting Time Comparison",
            color="Scenario",
            color_discrete_sequence=["#7F7F7F", "#FF7F0E"],
            text_auto='.2s'
        )
        st.plotly_chart(fig2, use_container_width=True)
        
    st.markdown("### Stage-Level Impact")
    scen_stage = stage_df[stage_df["scenario"] == scenario_id]
    
    if not scen_stage.empty and not baseline_stage.empty:
        # Merge baseline and scenario stage metrics
        merged_stages = pd.merge(
            baseline_stage[["stage", "mean_queue", "utilization_percent"]],
            scen_stage[["stage", "mean_queue", "utilization_percent"]],
            on="stage",
            suffixes=(" (Baseline)", " (Simulation)")
        )
        
        # Melt for plotting queue
        melted_queue = merged_stages.melt(
            id_vars=["stage"], 
            value_vars=["mean_queue (Baseline)", "mean_queue (Simulation)"],
            var_name="Run",
            value_name="Mean Queue Length"
        )
        # Clean names
        melted_queue["Run"] = melted_queue["Run"].apply(lambda x: "Baseline" if "Baseline" in x else selected_label)
        
        fig_queue = px.bar(
            melted_queue,
            x="stage",
            y="Mean Queue Length",
            color="Run",
            barmode="group",
            title=f"Queue Length Shift: Baseline vs {selected_label}",
            color_discrete_sequence=["#7F7F7F", "#2CA02C"]
        )
        st.plotly_chart(fig_queue, use_container_width=True)
